export const GET_WEATHER = "GET_WEATHER";
export const GET_WEEK_FORECAST = "GET_WEEK_FORECAST";
export const GET_TODAY_FORECAST = "GET_TODAY_FORECAST";
export const WEATHER_ERROR = "WEATHER_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
